### ISSUE TITLE
shogoki - Wrong calculation of compoundediterest in D3VaultFunding

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#102]
shogoki

medium

# Wrong calculation of compoundediterest in D3VaultFunding

## Summary

The compunded interest is miscalculated for any timeframe bigger than 2 seconds, resulting in loss of interests.

## Vulnerability Detail

In [D3VaultFunding.sol:getCompoundInterestRate](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L178-L189) the compounded interest rate should be calculated and returned.
Given is the interest rate per second `r` and the time in seconds `t`.
The general formula for this is `(1+r) ** t`. 
The function uses an if statement to check for special cases like `t<1`, meaning `t=0` where the result is simply `1` (`1e18` with decimals), and `t<2`, meaning `t=1` where the result is `1+r*t`.
For all other cases the function uses the following calculation

```solidity
    return 1e18 + r * t + r.powFloor(2) * t * (t - 1) / 2;
``` 

While this will give us the correct resut for `t=2`, it will return a wrong amount for all values of `t>2`.
The devs even state in the comment in [D3VaultFUnding.sol:L180](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L180) that the correct rearrangement of the formula is `(1+r)^t = 1 + rt + t*(t-1)*r^2/2! + t*(t-1)*(t-2)*r^3/3! + ... + t*(t-1)...*(t-n+1)*r^n/n!`

A short example demonstrates this. If we take `r=5` and `t=3` we get:

```plaintext
1.:

(1+r) ** t 
= (1+5) ** 3 
= 6 ** 3 
= 216

2.:

1 + r*t + r ** 2 * t * (t-1) /2 
= 1 + 5*3 + 5 ** 2 * 3 * (3-1) / 2
= 1 + 15 + 25 * 3 * 2 / 2
= 16 + 75 
= 91
```

This function is used inside `_accrueInterestForRead` and `getLatestBorrowIndex`.

## Impact

Too less interest accrued for all cases where the function is called for a value of `t>2` 

## Code Snippet

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L178-L189

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L347

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L157

## Tool used

Manual Review

## Recommendation

Use the correct formula for accruing interest

**Comment by Shogoki** [comment]
Escalate for 10USDC 
I think this should still be considered as a valid medium. 
even if we input values for `r<1` the functions will still deviate. Attached an example for `r=0.01` we can see it already deviates at `t=92` seconds and more so the higher t gets, of course.

![IMG_5551](https://github.com/sherlock-audit/2023-06-dodo-judging/assets/1040321/7b284c25-f25e-45a8-8538-7d0fcc06d774)
![IMG_5550](https://github.com/sherlock-audit/2023-06-dodo-judging/assets/1040321/8d7c3733-41b0-4596-aa8a-66d4ac7884bc)

**Comment by sherlock-admin2** [comment]
> Escalate for 10USDC 
> I think this should still be considered as a valid medium. 
> even if we input values for `r<1` the functions will still deviate. Attached an example for `r=0.01` we can see it already deviates at `t=92` seconds and more so the higher t gets, of course.
> 
> ![IMG_5551](https://github.com/sherlock-audit/2023-06-dodo-judging/assets/1040321/7b284c25-f25e-45a8-8538-7d0fcc06d774)
> ![IMG_5550](https://github.com/sherlock-audit/2023-06-dodo-judging/assets/1040321/8d7c3733-41b0-4596-aa8a-66d4ac7884bc)
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@Attens1423

**Comment by hrishibhat** [comment]
@Shogoki 
Additional Sponsor comment:
> Taylor's deviation from reality is normal, and this error is acceptable. Any loan agreement that calculates interest will encounter such errors, including Aave and Compound. We still consider this issue invalid.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue based on the Sponsor comment
https://github.com/sherlock-audit/2023-06-dodo-judging/issues/102#issuecomment-1661759713

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/102/#issuecomment-1650684810): rejected
