### ISSUE TITLE
osmanozdemir1 - An attacker can call `buyTokens` in the `D3Proxy.sol` with 1 wei and drain the contract as the `msg.value` is not checked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#120]
osmanozdemir1

high

# An attacker can call `buyTokens` in the `D3Proxy.sol` with 1 wei and drain the contract as the `msg.value` is not checked

## Summary
The `buyTokens()` function in the `D3Proxy.sol` contract doesn't check if the `msg.value` is enough to pay the price when the `fromToken` is ETH. This will cause anyone to buy any tokens with ETH without paying the actual price.

## Vulnerability Detail
There are two functions for buying & selling in the `D3Proxy.sol` contract. Users can buy or sell tokens and/or ETH. The vulnerability occurs if the `fromToken` is ETH in the `buyTokens()` function.

There are two options when users want to exchange their ETH with some other token. In the first option, users decide exactly how much ETH they want to sell, they call the `sellTokens()` function and get the tokens in exchange. This function checks if the user actually sent that amount of ETH.  
In the second option, users decide how many tokens they want to receive but they don't know how much ETH it will cost. They call the `buyTokens()` function, and the function calculates the `fromTokenAmount` meaning "You have to pay that much ETH to get that many tokens", but **never checks if the user sent enough ETH** as `msg.value`.

Here is the check that happens [in the sellTokens() function:](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L90-L92)

```solidity
// File: D3Proxy.sol
90.    if (fromToken == _ETH_ADDRESS_) {
91.-->     require(msg.value == fromAmount, "D3PROXY_VALUE_INVALID");
92.        receiveToAmount = ID3MM(pool).sellToken(to, _WETH_, toToken, fromAmount, minReceiveAmount, data);
```

Here is the [buyTokens() function](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L112-L132):

```solidity
// File: D3Proxy.sol
112.    function buyTokens(
113.        address pool,
114.        address to,
115.        address fromToken,
116.        address toToken,
117.        uint256 quoteAmount,
118.        uint256 maxPayAmount,
119.        bytes calldata data,
120.        uint256 deadLine
121.    ) public payable judgeExpired(deadLine) returns (uint256 payFromAmount) {
122.-->     if (fromToken == _ETH_ADDRESS_) {
123.-->         payFromAmount = ID3MM(pool).buyToken(to, _WETH_, toToken, quoteAmount, maxPayAmount, data);
124.-->         // multicall refund eth to user
125.        } else if (toToken == _ETH_ADDRESS_) {
126.            payFromAmount = ID3MM(pool).buyToken(address(this), fromToken, _WETH_, quoteAmount, maxPayAmount, data);
127.            _withdrawWETH(to, quoteAmount);
128.            // multicall withdraw weth to user
129.        } else {
130.            payFromAmount = ID3MM(pool).buyToken(to, fromToken, toToken, quoteAmount, maxPayAmount, data);
131.        }
132.    }
```

Now, let's check lines 122, 123 and 124 in the code above.

There are no checks that have been made in terms of `msg.value`. This function will call the `ID3MM(pool).buyToken()` function using `_WETH_` as `fromToken` in line 123 no matter how much ETH is sent. This call will trigger the [`buyToken()`](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Trading.sol#L129) function in the pool contract which will callback the proxy again in [line 150](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Trading.sol#L150C9-L150C88) with the `IDODOSwapCallback(msg.sender).d3MMSwapCallBack(fromToken, payFromAmount, data);`

The callback function in the proxy [will call](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L142) the `_deposit()` and here is the deposit function:  
[https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L213-L222](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L213C1-L222C6)

```solidity
// File: D3Proxy.sol   
   function _deposit(address from, address to, address token, uint256 value) internal {
-->     if (token == _WETH_ && address(this).balance >= value) {
            // pay with WETH9
-->         IWETH(_WETH_).deposit{value: value}(); // wrap only what is needed to pay
-->         IWETH(_WETH_).transfer(to, value);
        } else {
            // pull payment
            IDODOApproveProxy(_DODO_APPROVE_PROXY_).claimTokens(token, from, to, value);
        }
    }
```

As you can see in all the transaction flow above, there are no checks for `msg.value` during any part of the calls. The proxy contract's balance is checked before wrapping the ETH because it is assumed that the user already sent the value to the proxy contract.

Another thing I want to mention here is the comment in [line 124](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L124) of the vulnerable function and the comment in [line 188](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L188) just before `refundETH()` function. The developers already thought that the users have to send more ETH than the actual `payFromAmount` and refund them the difference, but maybe forgot to implement it.

```solidity
--> /// @dev when fromToken = ETH and call buyTokens, call this function to refund user's eth
    function refundETH() external payable {
        if (address(this).balance > 0) {
            _safeTransferETH(msg.sender, address(this).balance);
        }
    }
```

## Impact
An attacker can type any value as `quoteAmount` that worths less than ETH balance of the `D3Proxy.sol` to call the `buyTokens()` function. Due to lack of msg.value check, attacker will get that many tokens. Attacker can drain all the ETH balance of the `D3Proxy.sol` contract.

## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L112-L132

```solidity
// File: D3Proxy.sol
112.    function buyTokens(
113.        address pool,
114.        address to,
115.        address fromToken,
116.        address toToken,
117.        uint256 quoteAmount,
118.        uint256 maxPayAmount,
119.        bytes calldata data,
120.        uint256 deadLine
121.    ) public payable judgeExpired(deadLine) returns (uint256 payFromAmount) {
122.-->     if (fromToken == _ETH_ADDRESS_) {
123.-->         payFromAmount = ID3MM(pool).buyToken(to, _WETH_, toToken, quoteAmount, maxPayAmount, data);
124.-->         // multicall refund eth to user
125.        } else if (toToken == _ETH_ADDRESS_) {
126.            payFromAmount = ID3MM(pool).buyToken(address(this), fromToken, _WETH_, quoteAmount, maxPayAmount, data);
127.            _withdrawWETH(to, quoteAmount);
128.            // multicall withdraw weth to user
129.        } else {
130.            payFromAmount = ID3MM(pool).buyToken(to, fromToken, toToken, quoteAmount, maxPayAmount, data);
131.        }
132.    }
```

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L213-L222

```solidity
// File: D3Proxy.sol   
   function _deposit(address from, address to, address token, uint256 value) internal {
-->     if (token == _WETH_ && address(this).balance >= value) {
            // pay with WETH9
-->         IWETH(_WETH_).deposit{value: value}(); // wrap only what is needed to pay
-->         IWETH(_WETH_).transfer(to, value);
        } else {
            // pull payment
            IDODOApproveProxy(_DODO_APPROVE_PROXY_).claimTokens(token, from, to, value);
        }
    }
```

## Tool used

Manual Review

## Recommendation
I would recommend checking if the `msg.value` is enough to cover the expenses. Strict equality comparisons like `msg.value == payFromAmount` can't be used here because how much ETH will be required for this action is unknown before sending the transaction. That's why users have to send more than what they need and the function should refund the excess amount. An example implementation might be like this:

```solidity
//.... previous code parts...
121.    ) public payable judgeExpired(deadLine) returns (uint256 payFromAmount) {
122.        if (fromToken == _ETH_ADDRESS_) {
123.            payFromAmount = ID3MM(pool).buyToken(to, _WETH_, toToken, quoteAmount, maxPayAmount, data);
124.+++         require(msg.value >= payFromAmount)
125.+++         refundAmount = msg.value - payFromAmount
126.+++         _safeTransferETH(msg.sender, refundAmount)
//.... rest of the code...
//.... rest of the code...
```

**Comment by osmanozdemir1** [comment]
Escalate for 10 USDC

The issue I submitted was not about mistakenly deposited funds to the D3Proxy contract. It was about that there was not adequate checks if the user have sent enough value, and also `refundETH()` function is not called when it should have been called. 

There are two different functions which are `sellTokens()` and the `buyTokens()`. If the `fromToken` is ETH, the `msg.value` should be checked. The `msg.value` is checked [in the sellTokens() function](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L90-L92), but it is not checked in the `buyTokens()` function even though the `fromToken` is ETH.

As you said above, the D3Proxy should not have funds in normal operations. Normally user should send more ETH than the required amount, and the excess amount should be refunded. But the `refundETH()` function is not called during the `buyTokens()` function when the `fromToken` is ETH. Here is the snippet:

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L112-L132

```solidity
// File: D3Proxy.sol
112.    function buyTokens(
113.        address pool,
114.        address to,
115.        address fromToken,
116.        address toToken,
117.        uint256 quoteAmount,
118.        uint256 maxPayAmount,
119.        bytes calldata data,
120.        uint256 deadLine
121.    ) public payable judgeExpired(deadLine) returns (uint256 payFromAmount) {
122.-->     if (fromToken == _ETH_ADDRESS_) {
123.-->         payFromAmount = ID3MM(pool).buyToken(to, _WETH_, toToken, quoteAmount, maxPayAmount, data);
124.-->         // multicall refund eth to user
125.        } else if (toToken == _ETH_ADDRESS_) {
126.            payFromAmount = ID3MM(pool).buyToken(address(this), fromToken, _WETH_, quoteAmount, maxPayAmount, data);
127.            _withdrawWETH(to, quoteAmount);
128.            // multicall withdraw weth to user
129.        } else {
130.            payFromAmount = ID3MM(pool).buyToken(to, fromToken, toToken, quoteAmount, maxPayAmount, data);
131.        }
132.    }
```

In the lines 122-124 we can see that the refundETH should have been called but it is not called. Therefore the excess amount will be still in the D3Proxy contract. 

I agree that the mistakenly sent ETH is not the protocol's responsibility and the protocol wants users to interact with the proxy. So this is not mistakenly sent ETH, this is how the protocol wants users to interact. If a user wants to buy tokens using their ETH, they will not be refunded and they will lose funds. 

This situation also creates other problems.  
> In normal operations, D3Proxy does not retain any funds.

But because of a refund has not been made, the contract will still have some ETH left. 
* The first problem this will create is that anyone can call `buyTokens()` without sending ETH or only sending 1 wei as `msg.value` is not checked, and it may not revert because the contract might have enough ETH. So the caller will actually use other people's unrefunded ETH to buy some tokens.
* The second problem is that refundETH can be called by anyone and this issue #99 will be valid as the reason for invalidation was the assumption of D3Proxy can't have funds.

Because of these reasons, I believe not only this one but also the issue #99 should be valid high.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> The issue I submitted was not about mistakenly deposited funds to the D3Proxy contract. It was about that there was not adequate checks if the user have sent enough value, and also `refundETH()` function is not called when it should have been called. 
> 
> There are two different functions which are `sellTokens()` and the `buyTokens()`. If the `fromToken` is ETH, the `msg.value` should be checked. The `msg.value` is checked [in the sellTokens() function](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L90-L92), but it is not checked in the `buyTokens()` function even though the `fromToken` is ETH.
> 
> As you said above, the D3Proxy should not have funds in normal operations. Normally user should send more ETH than the required amount, and the excess amount should be refunded. But the `refundETH()` function is not called during the `buyTokens()` function when the `fromToken` is ETH. Here is the snippet:
> 
> https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L112-L132
> 
> ```solidity
> // File: D3Proxy.sol
> 112.    function buyTokens(
> 113.        address pool,
> 114.        address to,
> 115.        address fromToken,
> 116.        address toToken,
> 117.        uint256 quoteAmount,
> 118.        uint256 maxPayAmount,
> 119.        bytes calldata data,
> 120.        uint256 deadLine
> 121.    ) public payable judgeExpired(deadLine) returns (uint256 payFromAmount) {
> 122.-->     if (fromToken == _ETH_ADDRESS_) {
> 123.-->         payFromAmount = ID3MM(pool).buyToken(to, _WETH_, toToken, quoteAmount, maxPayAmount, data);
> 124.-->         // multicall refund eth to user
> 125.        } else if (toToken == _ETH_ADDRESS_) {
> 126.            payFromAmount = ID3MM(pool).buyToken(address(this), fromToken, _WETH_, quoteAmount, maxPayAmount, data);
> 127.            _withdrawWETH(to, quoteAmount);
> 128.            // multicall withdraw weth to user
> 129.        } else {
> 130.            payFromAmount = ID3MM(pool).buyToken(to, fromToken, toToken, quoteAmount, maxPayAmount, data);
> 131.        }
> 132.    }
> ```
> 
> In the lines 122-124 we can see that the refundETH should have been called but it is not called. Therefore the excess amount will be still in the D3Proxy contract. 
> 
> I agree that the mistakenly sent ETH is not the protocol's responsibility and the protocol wants users to interact with the proxy. So this is not mistakenly sent ETH, this is how the protocol wants users to interact. If a user wants to buy tokens using their ETH, they will not be refunded and they will lose funds. 
> 
> This situation also creates other problems.  
> > In normal operations, D3Proxy does not retain any funds.
> 
> But because of a refund has not been made, the contract will still have some ETH left. 
> * The first problem this will create is that anyone can call `buyTokens()` without sending ETH or only sending 1 wei as `msg.value` is not checked, and it may not revert because the contract might have enough ETH. So the caller will actually use other people's unrefunded ETH to buy some tokens.
> * The second problem is that refundETH can be called by anyone and this issue #99 will be valid as the reason for invalidation was the assumption of D3Proxy can't have funds.
> 
> Because of these reasons, I believe not only this one but also the issue #99 should be valid high.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jesusrod15** [comment]
agree with the sponsor as well as is invalid issue due that this functions must be called with multicall  https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L124

https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L128

**Comment by osmanozdemir1** [comment]
But there is an inconsistency here. As you can see in [this line](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L127) `_withdrawWETH()` is already called even though it is stated as _"multicall"_.
https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L127

But it is not implemented in the same way if the `fromToken` is ETH, and this function will act inconsistently.
 
So, if this function must be called with multicall all the time, `_withdrawWETH()` will be called twice. If it is not going to be called with multicall as you stated, then users will not get their ETH refunded as I explained in escalation.

**Comment by jesusrod15** [comment]
https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L127 

this is a internal function and withdraw WETH result fron this 

https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L125C47-L126C13

 in multicall  call
https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L198

for withdraw the Excess

**Comment by hrishibhat** [comment]
@osmanozdemir1 Confirming that this is a non issue?

**Comment by osmanozdemir1** [comment]
> @osmanozdemir1 Confirming that this is a non issue?

Sure, I it is not an issue if it will only be called with multicall.

**Comment by maarcweiss** [comment]
I also agree with non-issue because for this to happen users should send eth from another source than multicall, which is not intended by the protocol

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [osmanozdemir1](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/120/#issuecomment-1648360438): rejected
