### ISSUE TITLE
0x4db5362c - Wrong calculation of interest in D3VaultFunding#poolRepayAll()

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#127]
0x4db5362c

medium

# Wrong calculation of interest in D3VaultFunding#poolRepayAll()

## Summary
The interests of the pool repaid is wrongly calculated in `D3VaultFunding#poolRepayAll()`.

## Vulnerability Detail
`poolRepayAll()` calls `_poolRepayAll()` to repay all debt in `token`, but in [L124](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L124), the total repay amount was wrongly assigned to `interests`

    uint256 interests = amount;
## Impact
The emitted event carries the wrong description of interests repaid. 

## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L124

    uint256 interests = amount;
## Tool used

Manual Review

## Recommendation
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L124
Change the code in L124 as below:

    uint256 interests = amount - record.amount;

**Comment by 0xffff11** [comment]
Agree with non-duplication.

**Comment by IAm0x52** [comment]
Fix looks good. Interest calculation has been corrected
