### ISSUE TITLE
twcctop - Pool Repayment Allowed During Liquidation Process

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#131]
twcctop

high

# Pool Repayment Allowed During Liquidation Process

## Summary
During the DODO team liquidation process, the pool is able to repay even when it is in a state of liquidation. The `D3VaultFunding#poolRepay` function does not include a check to verify if the pool is currently in liquidation. This poses a risk because there are two steps involved in the liquidation process, and if the pool repays during the gap between the `startLiquidation` and `finishLiquidation` steps, it will still be liquidated.

## Vulnerability Detail
The vulnerability lies in the `D3VaultFunding#poolRepay` function. This function allows the pool to repay a specified amount of tokens. However, it lacks a validation step to ensure that the pool is not in the process of liquidation.

## Impact
The impact of this vulnerability is that a pool can repay tokens even when it is undergoing liquidation. This behavior is not intended and can lead to undesired consequences. If the pool repays during the liquidation process, it will still be liquidated, which can have adverse effects on the system's stability and integrity.

## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L117-L152 
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L65-L85
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L94

```solidity
function poolRepay(address token, uint256 amount) external nonReentrant allowedToken(token) onlyPool {
  // Repayment logic
  ...
}

function startLiquidation(address pool) external onlyLiquidator nonReentrant { 
...
}
function finishLiquidation(address pool) external onlyLiquidator nonReentrant { 
...
}
```

## Tool used
Manual Review

## Recommendation
To address this vulnerability, it is recommended to add a check in the `D3VaultFunding#poolRepay` function to verify if the pool is currently in the process of liquidation. If the pool is in liquidation, the function should reject the repayment request. This will ensure that pools can only repay when they are not undergoing liquidation, preventing undesired liquidation scenarios.

**Comment by IAm0x52** [comment]
Escalate

This is invalid. `D3VaultFunding#poolRepay` has the modifier `onlyPool` which only means it can only be called by the pool itself. The pool has two functions to repay which are [repay](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L31-L37) and [repayAll](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L40-L46). Both of which have the `poolOngoing` modifier which prevents repayment if the pool is undergoing liquidation.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is invalid. `D3VaultFunding#poolRepay` has the modifier `onlyPool` which only means it can only be called by the pool itself. The pool has two functions to repay which are [repay](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L31-L37) and [repayAll](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L40-L46). Both of which have the `poolOngoing` modifier which prevents repayment if the pool is undergoing liquidation.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by twcctop** [comment]
agree ,this is invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the Escalation

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/131/#issuecomment-1650817002): accepted

**Comment by IAm0x52** [comment]
Fix looks good though the check here is redundant.
