### ISSUE TITLE
stuart_the_minion - stuart_the_minion - Decimals discrepancies exist when calculating used quota in D3UserQuota::getUserQuota()

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#134]
stuart_the_minion

high

# stuart_the_minion - Decimals discrepancies exist when calculating used quota in D3UserQuota::getUserQuota()

stuart_the_minion

High

# Decimals discrepancies exist when calculating user quota in D3UserQuota::getUserQuota()

## Summary

When calculating used quota in `D3UserQuota::getUserQuota()`, cumulative `totalBalance` is incorrectly divided by `10^tokenDecimals`, and this results in decimals discrepancy between `usedQuota` and the result of `D3UserQuota::calculateQuota()`.
 
## Vulnerability Detail

[DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L75C9-L84C10](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L75C9-L84C10)

```solidity
        for (uint256 i = 0; i < tokenList.length; i++) {
            address _token = tokenList[i];
            (address assetDToken,,,,,,,,,,) = d3Vault.getAssetInfo(_token);
            uint256 tokenBalance = IERC20(assetDToken).balanceOf(user);
            if (tokenBalance > 0) {
                tokenBalance = tokenBalance.mul(d3Vault.getExchangeRate(token));
                (uint256 tokenPrice, uint8 priceDecimal) = ID3Oracle(d3Vault._ORACLE_()).getOriginalPrice(_token);
                usedQuota = usedQuota + tokenBalance * tokenPrice / 10 ** (priceDecimal+tokenDecimals);
            }
        }
```

In line 82, `tokenBalance` is divided by `10 ** (priceDecimal+tokenDecimals)` and that means the decimals of `usedQuota` is just 1, not `10**tokenDecimals`.

When calculating quota in `calculateQuota()`, decimals of `tokenBalance` of `_QUOTA_TOKEN_HOLD` is the one that is multiplied by `10**"decimals of quota token hold"`.

```solidity
    function calculateQuota(address user) public view returns (uint256 quota) {
        uint256 tokenBalance = IERC20(_QUOTA_TOKEN_HOLD).balanceOf(user);
        for (uint256 i = 0; i < quotaTokenHoldAmount.length; i++) {
            if (tokenBalance < quotaTokenHoldAmount[i]) {
                return quota = quotaTokenAmount[i];
            }
        }
        quota = quotaTokenAmount[quotaTokenAmount.length - 1];
    }
```

This means, in line 92, the discrepancy exists in the subtraction `(calculateQuota(user) - usedQuota)`. And this subtraction is further multiplied by `10 ** (_priceDecimal + tokenDecimals)`.

```solidity
return (calculateQuota(user) - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;
```

## Impact

`getUserQuota()` function may return unexpected big value by this issue and this will make `checkQuota()` function almost always `true`

## Code Snippet

[DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L75C9-L84C10](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L75C9-L84C10)

## Tool used

Manual Review

## Recommendation

At line 82, I'd suggest removing `tokenDecimals` from power of 10.
```solidity
usedQuota = usedQuota + tokenBalance * tokenPrice / 10 ** (priceDecimal);
```

In this case, at line 90 and 92, we might need to remove tokenDecimals from powers, either.
```solidity
return (gloablQuota[token] - usedQuota) * 10 ** (_priceDecimal) / _tokenPrice;
```

```solidity
return (calculateQuota(user) - usedQuota) * 10 ** (_priceDecimal) / _tokenPrice;
```

**Comment by IAm0x52** [comment]
Escalate

This is not a dupe of #193. This is invalid. Price calculations are correct as is demonstrated by test cases

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not a dupe of #193. This is invalid. Price calculations are correct as is demonstrated by test cases

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on Sponsor and Escalation

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/134/#issuecomment-1650736941): accepted
