### ISSUE TITLE
seeques - Total borrow amount is not updated upon liquidation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#157]
seeques

high

# Total borrow amount is not updated upon liquidation

## Summary
In public `liquidate()` function the `assetInfo[debt].totalBorrows` is not updated, which makes a descrepancy between the actual amount borrowed and the one that is stored in a struct.
## Vulnerability Detail
When a user calls `liquidate()` function on a specific pool, he pays the pool's debt in debtToken thus decreasing the token's borrow amount. However, the `assetInfo[debt].totalBorrows` is not decreased by the `debtToCover` amount.
## Impact
Not decreasing the totalBorrows of a specific token upon liquidation leads to incorrect calculation of [totalReserves](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L159) (they would be bigger than they should), higher utilization ratio and incorrect amount of dToken minted or underlying transfered.
## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L30-L61
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L159
## Tool used

Manual Review

## Recommendation
Decrease the total borrows by `debtToCover` in `liquidate()` function:
```solidity
info.totalBorrows -= debtToCover;
```

Duplicate of #46

**Comment by seeques** [comment]
@hrishibhat I think the Reward label was mistakenly removed for this issue as this is a duplicate of #46. Just thought I mention it :)

**Comment by IAm0x52** [comment]
Same issue as #46 and same fix PR
