### ISSUE TITLE
0xG0P1 - The use of the `liquidate` function in the `D3VaultLiquidation.sol` contract can result in substantial financial losses for the liquidator.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#163]
0xG0P1

medium

# The use of the `liquidate` function in the `D3VaultLiquidation.sol` contract can result in substantial financial losses for the liquidator.

## Summary
The public `liquidate` function in the `D3VaultLiquidation.sol` contract may result in a lower `collateralAmount` for the liquidator than what he should actually receive, potentially causing financial losses.
## Vulnerability Detail
Within the `liquidate` function of the `D3VaultLiquidation.sol` contract, the liquidator is intended to receive a  `collateralAmountMax` in exchange for the `debtToCover` amount they transfer. However, there is a discrepancy where the liquidator actually receives a  `collateralAmount` instead. The specified `collateralAmount` parameter supposed to serve as a means of controlling slippage. If the liquidator should be entitled to an amount greater than the specified `collateralAmount`, denoted as `collateralAmountMax`, the difference between the expected and received amounts results in a loss of funds for the liquidator, specifically equivalent to `collateralAmountMax - collateralAmount`.
## Impact
The liquidator runs the risk of receiving less funds than they should actually obtain.
## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L48
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L59
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L30-L61
## Tool used

Manual Review

## Recommendation
Transfer the corresponding collateral for the `debtToCover` if `collateralAmountMax` exceeds `collateralAmount` to avoid potential loss.

**Comment by SteveHarrington0** [comment]
Escalate
why this  labeled as Non-Reward and  the liquidator who attempts to liquidate by supplying debtToCover amount should receive the  collateralAmountMax amount instead he is getting collateralAmount which is ofcourse leads to loss for the liquidator

**Comment by sherlock-admin2** [comment]
> Escalate
> why this  labeled as Non-Reward and  the liquidator who attempts to liquidate by supplying debtToCover amount should receive the  collateralAmountMax amount instead he is getting collateralAmount which is ofcourse leads to loss for the liquidator

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
The liquidator receives the amount they specify as long as it is <= the max limit.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SteveHarrington0](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/163/#issuecomment-1647771943): rejected
