### ISSUE TITLE
josephdara - userFunds can be lost by calling makerDeposit

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#174]
josephdara

medium

# userFunds can be lost by calling makerDeposit

## Summary
In the ```D3Proxy``` contract, there are two deposit functions that can be used by a user or maker, However, none of this functions has a check to restrict who can call this function. 
This would not be an issue for the user except for the fact that this function makes a call to two different contracts. 
UserDeposits are make a call to the ```D3_VAULT``` 
```solidity
    function userDeposit(address user, address token, uint256 amount) external payable {
        if (token == _ETH_ADDRESS_) {
            require(msg.value == amount, "D3PROXY_PAYMENT_NOT_MATCH");
            _deposit(msg.sender, _D3_VAULT_, _WETH_, amount);
            ID3Vault(_D3_VAULT_).userDeposit(user, _WETH_);
        } else {
            _deposit(msg.sender, _D3_VAULT_, token, amount);
            ID3Vault(_D3_VAULT_).userDeposit(user, token);
        }
    }
```
However the makerDeposits call  the D3MM pools directly with the ```makerDeposit``` function.
```solidity

    function makerDeposit(address pool, address token, uint256 amount) external payable {
        //@audit-issue it should require msg.sender is pool owner
        if (token == _ETH_ADDRESS_) {
            require(msg.value == amount, "D3PROXY_PAYMENT_NOT_MATCH");
            _deposit(msg.sender, pool, _WETH_, amount);
            ID3MM(pool).makerDeposit(_WETH_);
        } else{
            _deposit(msg.sender, pool, token, amount);
            ID3MM(pool).makerDeposit(token);
        }
    }
```
The makerDeposit function in the D3MM pool has no validations for the msg.sender so the function would go through.
 

## Impact
Users will loose their funds if function is called, even though it should revert on the contract level
It is stated in the code comment as well as the DODOV3 docs that this function is for pool owners

## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L170-L183
## Tool used

Manual Review

## Recommendation
The owner values for D3MM pools are public, so a check can be easily done to ensure that users do not deposit.
```solidity
    function makerDeposit(address pool, address token, uint256 amount) external payable {
        //@audit-issue it should require msg.sender is pool owner
        require(ID3MM(pool)._OWNER_() == msg.sender);
        if (token == _ETH_ADDRESS_) {
            require(msg.value == amount, "D3PROXY_PAYMENT_NOT_MATCH");
            _deposit(msg.sender, pool, _WETH_, amount);
            ID3MM(pool).makerDeposit(_WETH_);
        } else{
            _deposit(msg.sender, pool, token, amount);
            ID3MM(pool).makerDeposit(token);
        }
    }
```
NB this solution adds the 
```solidity
    function _OWNER_() external view returns (address);
```
to the interface since ```_OWNER_``` is already a public state variable.

**Comment by Josephdara** [comment]
Escalate
This issue was excluded without judging. 
The function should revert if called by anyone except the pool owner.

**Comment by sherlock-admin2** [comment]
> Escalate
> This issue was excluded without judging. 
> The function should revert if called by anyone except the pool owner. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Users calling another function by mistake is not a valid issue.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [josephdara](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/174/#issuecomment-1648302689): rejected
