### ISSUE TITLE
lemonmon - Wrong pool potentially being removed by the function `D3Vault.removeD3Pool`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#184]
lemonmon

high

# Wrong pool potentially being removed by the function `D3Vault.removeD3Pool`

## Summary

When calling the function `D3Vault.removeD3Pool` it can happen that the wrong pool is being removed.

## Vulnerability Detail

If the `creator` has multiple pools stored inside `creatorPoolMap[creator]`, the `D3Vault.removeD3Pool` function will always remove the last pool from `creatorPoolMap[creator]`. The `pool` param from `D3Vault.removeD3Pool()` is being ignored, thus potentially removing the wrong pool.

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultStorage.sol#L35

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L36

When the `pool` to remove is found inside the `poolList` (line 45 D3Vault.sol), the code wants to set the last element of the `poolList` to the current index `i` of the `pool` that should be removed (line 46 D3Vault.sol):

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L45-L46

But instead of assigning it via `=`, the comparison operator `==` is used, which doesn't change the elements inside the `poolList` array. Then the unchanged `poolList` is assigned to the `creatorPoolMap[creator]`:

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L47

This means that the array of pools in `creatorPoolMap[creator]` is still the same as before without any changes.

Then the last element of the pools array in `creatorPoolMap[creator]` is being removed:

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L48

Thus potentially the wrong pool was removed.

## Impact

The wrong pool can get removed when calling `D3Vault.removeD3Pool()`.

If the wrong pool gets removed, the actual `pool` that was supposed to be removed cannot be removed anymore, because `allPoolAddrMap[pool]` is set to false (line 40 D3Vault), making line 37 in D3Vault.sol always revert when trying to remove the pool.

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L37

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L40

Additionally if the wrong pool gets removed, the `allPoolAddrMap[pool]` is set to false for the `pool` that should have been removed (line 40 D3Vault), which means that the `pool` can be added again as a duplicate, because line 14 and line 22 in D3Vault doesn't revert anymore.

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L40

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L14

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L22

## Code Snippet

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultStorage.sol#L35

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L36

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L45-L48

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L37

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L40

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L14

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L22

## Tool used

Manual Review

## Recommendation

The correct operator `=` should be used in D3Vault.sol line 46.

```solidity
// D3Vault
// removeD3Pool
46                poolList[i] = poolList[poolList.length - 1];
```

**Comment by osmanozdemir1** [comment]
Escalate for 10 USDC

I agree that there is a bug but I don't think it is a valid bug according to Sherlock rules.

`removeD3Pool()` updates two different mappings: One of them is `allPoolAddrMap` and the other one is `creatorPoolMap`. When this function is called, the right pool is removed from the `allPoolAddrMap` in the [line 40](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L40), but wrong pool is removed in the `creatorPoolMap`.

`creatorPoolMap` mapping is never used in any function that interacts with funds etc, or it is never used in any _"require"_ statement. It is only used while adding new pool or removing pool, which will only result wrong creator pool array.

The actual pool mapping that is widely used in every crucial interaction is `allPoolAddrMap`, and this mapping is updated in a right way. For example, these interactions are: [onlyPool()](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultStorage.sol#L84) modifier in the `D3VaultStorage.sol`, or [d3MMSwapCallBack()](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L139) in the `D3Proxy.sol` etc.

I agree that there is a bug and the wrong pool is removed in the `creatorPoolMap`, and this will result the creator pool array to be wrong. But it will not harm the protocol other than that. This issue can be low/informational, not high.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> I agree that there is a bug but I don't think it is a valid bug according to Sherlock rules.
> 
> `removeD3Pool()` updates two different mappings: One of them is `allPoolAddrMap` and the other one is `creatorPoolMap`. When this function is called, the right pool is removed from the `allPoolAddrMap` in the [line 40](https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L40), but wrong pool is removed in the `creatorPoolMap`.
> 
> `creatorPoolMap` mapping is never used in any function that interacts with funds etc, or it is never used in any _"require"_ statement. It is only used while adding new pool or removing pool, which will only result wrong creator pool array.
> 
> The actual pool mapping that is widely used in every crucial interaction is `allPoolAddrMap`, and this mapping is updated in a right way. For example, these interactions are: [onlyPool()](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultStorage.sol#L84) modifier in the `D3VaultStorage.sol`, or [d3MMSwapCallBack()](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Proxy.sol#L139) in the `D3Proxy.sol` etc.
> 
> I agree that there is a bug and the wrong pool is removed in the `creatorPoolMap`, and this will result the creator pool array to be wrong. But it will not harm the protocol other than that. This issue can be low/informational, not high.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Nabeel-javed** [comment]
in this way I can say that there isn't any need for `creatorPoolMap` mapping and it should be removed, imo.

**Comment by osmanozdemir1** [comment]
They probably created this mapping for users to be able to query the creator pools easily with public getter functions. But as I mentioned above, it will not cause a harm other than returning a wrong creator pool array in the getter function.

**Comment by lemonmon1984** [comment]
I would still consider this to be at least medium.

**Comment by Nabeel-javed** [comment]
atleast medium or high

**Comment by fatherGoose1** [comment]
> I would still consider this to be at least medium.

Do you have a counter-argument explaining how this can cause harm to the protocol?

**Comment by maarcweiss** [comment]
I agree with the Watson's escalation. The error keeps a wrong mapping with no impact on the protocol itself. Low

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Agree that this is a bug, but the impact as mentioned in the escalation is low. The impact of having incorrect list of pools in `creatorPoolMap` can be low as this is not used in the code anywhere that would cause damage.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [osmanozdemir1](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/184/#issuecomment-1648524454): accepted

**Comment by IAm0x52** [comment]
Fix looks good. The incorrect `==` has been replaced with the correct `=`
