### ISSUE TITLE
0x52 - calculateQuota can easily be bypassed via flashloans or borrows

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#196]
0x52

medium

# calculateQuota can easily be bypassed via flashloans or borrows

## Summary

D3UserQuota#calculateQuota adjusts user quota based on the number of tokens they are holding. This can easily be bypassed via flashloans or borrows to temporarily increase their balance. After they have deposited they can simply repay the loan and benefit from the higher quota that should be reserved for holders.

## Vulnerability Detail

See summary

## Impact

Balance based quota is broken by flashloans and borrows

## Code Snippet

[D3UserQuota.sol#L104-L112](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L104-L112)

## Tool used

Manual Review

## Recommendation

Require users to stake tokens directly with this contract and check quota when withdrawing stake

**Comment by IAm0x52** [comment]
Escalate

I think this should be given a second look. This allows user to easily bypass any quota restrictions and make the quote completely useless in most scenarios. Should be medium since functionality is effectively broken

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this should be given a second look. This allows user to easily bypass any quota restrictions and make the quote completely useless in most scenarios. Should be medium since functionality is effectively broken

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@Attens1423

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low based on the Sponsor's comment. Since there is no loss of funds and this would be used for pledged tokens. This is a valid issue but a low impact
Sponsor comment:
> UserQuota will not cause any financial loss to users. We are planning to use pledged tokens as the basis for quota assessment. We acknowledge this issue, but currently have no plans to make any modifications.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/196/#issuecomment-1650807619): rejected
