### ISSUE TITLE
0xdice91 - Missing `onlyRouter` modifier in `D3VaultLiquidation.liquidateByDODO`.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#202]
0xdice91

medium

# Missing `onlyRouter` modifier in `D3VaultLiquidation.liquidateByDODO`.

## Summary
The modifier `onlyRouter` is missing in the function `D3VaultLiquidation.liquidateByDODO`
## Vulnerability Detail
The modifier `onlyRouter` used to check that the inputted router is among the list of allowed routers is not added to this function.
```solidity
modifier onlyRouter(address router) {
        require(allowedRouter[router], Errors.NOT_ALLOWED_ROUTER);
        _;
    }
```
The function `liquidateByDODO` uses a router to carry out liquidation so the modifier `onlyRouter` is needed to ensure that the trusted router is used.
```solidity
function liquidateByDODO(
        address pool,
        LiquidationOrder calldata order,
        bytes calldata routeData,
        address router
    ) external onlyLiquidator nonReentrant {
        uint256 toTokenReserve = IERC20(order.toToken).balanceOf(address(this));
        uint256 fromTokenValue = DecimalMath.mul(ID3Oracle(_ORACLE_).getPrice(order.fromToken), order.fromAmount);
//More Code ....
}
```
## Impact
Without proper validation of the router being used, a risk of unwanted behaviour and the wrong router being used is present.
## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultStorage.sol#L78-L81C6

https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L86C1-L95

## Tool used
Manual Review

## Recommendation
The `onlyRouter` modifier should be added to validate the inputted router.
```solidity
    function liquidateByDODO(
        address pool,
        LiquidationOrder calldata order,
        bytes calldata routeData,
        address router
    ) external onlyLiquidator onlyRouter(router) nonReentrant {
        uint256 toTokenReserve = IERC20(order.toToken).balanceOf(address(this));
        uint256 fromTokenValue = DecimalMath.mul(ID3Oracle(_ORACLE_).getPrice(order.fromToken), order.fromAmount);
//More Code ....
}
```

Duplicate of #10

**Comment by IAm0x52** [comment]
Fixed in [PR#28](https://github.com/DODOEX/new-dodo-v3/pull/28)

Fix looks good. `D3VaultLiquidation#liquidateByDODO` now has the `onlyRouter` modifier
