### ISSUE TITLE
shogoki - DoS - Vault Deposits can be blocked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#218]
shogoki

medium

# DoS - Vault Deposits can be blocked

## Summary

A malicious user or attacker can DoS the deposit function of the D3Vault contract.

## Vulnerability Detail

In D3VaultFunding.sol´s `userDeposit` function there is a check if the amount to be deposited is not exceeding the max Deposit amount.
The amount is calculated by the actual balance the contract holds - the accounted balance inside the contract.
An malicious user or attacker can transfer an amount of tokens, that would exceed the max amount to prevent any user from depsiting to the vault.

## Impact

No user can Deposit the DOSed Token to the vault.

## Code Snippet

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L34

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L38

## Tool used

Manual Review

## Recommendation

Do not use the actual balance to determine what the user has deposited.

**Comment by IAm0x52** [comment]
Fixed in [PR#48](https://github.com/DODOEX/new-dodo-v3/pull/48)

Fix looks good. Owner can now withdraw excess amount to prevent this.
