### ISSUE TITLE
josephdara - Liquidation undercuts the liquidator

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#229]
josephdara

medium

# Liquidation undercuts the liquidator

## Summary
The ```liquidate``` function handles liquidation and retrieval of collateral. However, liquidations do not favor the liquidator due to this 
```solidity
        uint256 collateralTokenPrice = ID3Oracle(_ORACLE_).getPrice(collateral);
        uint256 debtTokenPrice = ID3Oracle(_ORACLE_).getPrice(debt);
        uint256 collateralAmountMax = debtToCover.mul(debtTokenPrice).div(collateralTokenPrice.mul(DISCOUNT));

        require(collateralAmount <= collateralAmountMax, Errors.COLLATERAL_AMOUNT_EXCEED);
```
## Vulnerability Detail
Due to market conditions or mathematical errors,  the ```collateralAmount ``` initially inputted by the liquidator can be considerably smaller than the ```collateralAmountMax ``` therefore, Instead of getting the max calculated reward which is safe to pay for their liquidations, they get transferred whatever amount they inputted and still cover the ```debtToCover``` used to get the max amount
This can be seen here is the initial collateralAmount being transferred
```solidity
  IERC20(debt).transferFrom(msg.sender, address(this), debtToCover);

        record.amount = borrows - debtToCover;
        record.interestIndex = info.borrowIndex;
        IERC20(collateral).transferFrom(pool, msg.sender, collateralAmount);
        ID3MM(pool).updateReserveByVault(collateral);
```
## Impact
Users can get less collateral for debt payment. Eventually the pool negative worth can be fully repaid and the collateral unpaid to the liquidator would remain in the DD3 pool contract. 
## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L24-L61
## Tool used

Manual Review

## Recommendation
I believe that the collateral should be calculated within the function. On the otherhand, a minimumcollateralAmount can be introduced to check that atleast a minimum value of collateral is gotten. Therefore we check for a minimum value and send the contract calculated amount

**Comment by Josephdara** [comment]
Escalate
This issue was excluded as well. 
Liquidators can potentially receive a far less collateral amount from liquidation due to price action as well as time between when a transaction is sent and when it's added to the mempool.

**Comment by sherlock-admin2** [comment]
> Escalate
> This issue was excluded as well. 
> Liquidators can potentially receive a far less collateral amount from liquidation due to price action as well as time between when a transaction is sent and when it's added to the mempool. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is user input validation. The liquidator inputting an incorrect `collteralAmount` is not a valid medium/high issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [josephdara](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/229/#issuecomment-1649606509): rejected
