### ISSUE TITLE
0xrobsol - Global Quota Exceeded due to Price Changes

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#231]
0xrobsol

high

# Global Quota Exceeded due to Price Changes

## Summary
There is a potential issue in the getUserQuota function of the D3UserQuota contract, where the usedQuota can become greater than gloablQuota[token] due to price fluctuations of the deposited asset.

## Vulnerability Detail
In the getUserQuota function, the used quota is calculated based on the current price of the deposited assets. If the price of these assets rises significantly between deposits, usedQuota can exceed gloablQuota[token]. This is because usedQuota is a reflection of the total value of the user's deposit in USD, and if the asset's price rises, the USD value of the deposit will rise correspondingly.

For instance, if a user initially deposits 1000 units of an asset when the price is 1 USD, the usedQuota will be 1000 USD. If the price of the asset doubles to 2 USD, the usedQuota will rise to 2000 USD, potentially exceeding gloablQuota[token] that was set to 1000 USD.

## Impact
This allows users to deposit more than their quota, as the checkQuota function checks whether the deposit amount is less than or equal to getUserQuota, which could return a value greater than gloablQuota[token] due to the issue described above.

## Code Snippet

https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L90

## Tool used

Manual Review

## Recommendation
Implement a require check to ensure that gloablQuota is always greater than usedQuota. This will prevent the possibility of usedQuota exceeding gloablQuota due to price increases, thereby ensuring that users cannot deposit more than their allowed quota.

`
if (isUsingQuota[token]) {
            if (isGlobalQuota[token]) {
                require(gloablQuota >= usedQuota, "Used quota should not exceed global quota");
                return (gloablQuota[token] - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;

            } else {
                return (calculateQuota(user) - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;
            }
        } else {
            return type(uint256).max;
        }
`

**Comment by IAm0x52** [comment]
Escalate

This is not a dupe of #193. This is a separate issue. It discusses going over the quota due to price fluctuations which is expected behavior due to collateral being valued in USD

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not a dupe of #193. This is a separate issue. It discusses going over the quota due to price fluctuations which is expected behavior due to collateral being valued in USD

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Agree with the Lead Watson as this seems to be the expected behaviour. The quota check is required only for deposit which works as intended and is satisfied at the time of deposit.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/231/#issuecomment-1650735804): accepted
