### ISSUE TITLE
traceurl - Need check inLiquidation status in liquidateByDODO()

### ISSUE THREAD

**Issue by traceurl** [sherlock-audit/2023-06-dodo-judging#243]
low

## Summary
In D3VaultLiquidation, we need to check if pool is in liquidation process when calling liquidateByDODO().

## Vulnerability Detail
https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L87-L115

## Impact
If we don't check this, the liquidator can call liquidateByDODO() even when pool is not in liquidation process. This gives DODO team too much permission.

## Tool Used
Manual Review

## Recommandation
Add this line in the begin of the function
```solidity
require(ID3MM(pool).isInLiquidation(), Errors.NOT_IN_LIQUIDATION);
```

**Comment by IAm0x52** [comment]
Fixed in [PR#34](https://github.com/DODOEX/new-dodo-v3/pull/34)

Fix looks good. liquidateByDODO() now confirms that the pool is in liquidation
