### ISSUE TITLE
attens - RemovePool event duplicated

### ISSUE THREAD

**Issue by Attens1423** [sherlock-audit/2023-06-dodo-judging#244]
low

# RemovePool event duplicated
## Summary
Event RemovePool should be emitted once.

## Vulnerability Detail
In remove pool procession, owner call these funcitons: removeD3Pool() -> liquidateByDODO() -> finishPoolRemove()
In removeD3Pool(), contract sends an event: https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L49C6-L49C39
In finishPoolRemove(), contract sends the same event again: https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3Vault.sol#L63
And the parameter of the event, pool, is always address(0) in the finishPoolRemove()

## Impact
Sending wrong event info

## Tool Used
Manual Review

## Recommandation
1. Delete the event in removeD3Pool()
2. fix event in finishPoolRemove()
```solidity
ID3MM(_PENDING_REMOVE_POOL_).finishLiquidation();
emit RemovePool(_PENDING_REMOVE_POOL_);
_PENDING_REMOVE_POOL_ = address(0);
 ```

**Comment by IAm0x52** [comment]
Fix looks good. Duplicate event has been removed
