### ISSUE TITLE
dirk_y - Malicious user can prevent DODO from finishing a liquidation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#48]
dirk_y

medium

# Malicious user can prevent DODO from finishing a liquidation

## Summary
A malicious user can frontrun calls from DODO to `finishLiquidation`, during which they send supported ERC20 tokens to the pool and cause the `finishLiquidation` call to fail in a normal liquidation scenario. 

## Vulnerability Detail
When a pool has bad debt the pool is able to be liquidated by DODO. This involves a series of calls:
1. `startLiquidation`
2. `liquidateByDODO`
3. `finishLiquidation`

During step 1 a liquidation target is set for each token:

```solidity
        for (uint256 i; i < tokenList.length; i++) {
            address token = tokenList[i];
            AssetInfo storage info = assetInfo[token];
            BorrowRecord storage record = info.borrowRecord[pool];
            uint256 debt = record.amount.div(record.interestIndex == 0 ? 1e18 : record.interestIndex).mul(info.borrowIndex).mul(ratio);
            liquidationTarget[pool][token] = debt;
        }
```

The liquidation target is 0 for tokens that have not been borrowed by the pool and non-zero for tokens that have been borrowed.

Step 2 of the above list is where DODO actually performs the liquidation step for each relevant token. Finally in step3 the liquidation is finished and any debt from the liquidation is repaid and the `totalBorrows` amount written down. During this `finishLiquidation` call the following logic is performed for each token:

```solidity
            uint256 balance = IERC20(token).balanceOf(pool);
            uint256 debt = liquidationTarget[pool][token];
            int256 difference = int256(balance) - int256(debt);
            if (difference > 0) {
                require(!hasNegativeBalance, Errors.LIQUIDATION_NOT_DONE);
                hasPositiveBalance = true;
            } else if (difference < 0) {
                require(!hasPositiveBalance, Errors.LIQUIDATION_NOT_DONE);
                hasNegativeBalance = true;
                debt = balance; // if balance is less than target amount, just repay with balance
            }
```

As is also demonstrated in the associated tests, during the liquidation of the pool the normal behaviour would be to have some slippage, but still have the "in token" value to be greater than 95% of the "out token" value. In this case where value x is 95 < x < 100, the `difference` value in the above logic is < 0. Now, if `difference > 0` for any other token then the execution will revert.

A malicious user can use this to their advantage by simply transferring an arbitrary amount of any other supported ERC20 token to the pool to create a token where `balance > debt`. In fact this can be demonstrated with a very small change to an existing test:

```diff
diff --git a/new-dodo-v3/test/DODOV3MM/D3Vault/D3VaultLiquidation.t.sol b/new-dodo-v3/test/DODOV3MM/D3Vault/D3VaultLiquidation.t.sol
index c1d9304..2429d92 100644
--- a/new-dodo-v3/test/DODOV3MM/D3Vault/D3VaultLiquidation.t.sol
+++ b/new-dodo-v3/test/DODOV3MM/D3Vault/D3VaultLiquidation.t.sol
@@ -306,7 +306,9 @@ contract D3VaultLiquidationTest is TestContext {
         // positive net: 1 token1, 50 token3
         // negative net: 5 token2
         contextBadDebt();
-        token1.mint(address(d3MM), 1);
+        token1.mint(user1, 10 ether);
+        vm.prank(user1);
+        token1.transfer(address(d3MM), 1);
         
         vm.prank(liquidator);
         d3Vault.startLiquidation(address(d3MM));

```

DODO could eventually finish the liquidation by ensuring that the `difference` was positive for every token, however this would involve having a slippage > 100 where you're effectively paying a premium for every token. In reality this premium would be negligible, so the main issue for DODO is the increase in time and gas to finish a liquidation.

## Impact
A malicious user can temporarily prevent DODO from finishing a liquidation, trapping funds that should be in the vault in a pool instead (so the funds cannot be used by other pools). The user could specifically frontrun `finishLiquidation` calls to gas grief DODO and depending on the number of supported ERC20 tokens they could repeat this attack multiple times. 

During this process `totalBorrows` is also greater than it should be, so LPs are earning more interest than they should be (which negatively impacts the last redeemer of pTokens).

## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L126
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L129-L136
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultLiquidation.sol#L83

## Tool used
Manual Review

## Recommendation
Because the `liquidateByDODO` method includes a call to update the reserves of the pool for both the "to" and "from" token, the following line in `finishLiquidation` should be changed from:

```solidity
uint256 balance = IERC20(token).balanceOf(pool);
```

to:

```solidity
uint256 balance = ID3MM(pool).getTokenReserve(token);
```

**Comment by djb15** [comment]
Escalate

Firstly this isn't a duplicate of #131.

Regarding the comment from the sponsor, I don't think this is true as you wouldn't be able to perform the swapping from token to token due to the `poolOngoing` modifier on the `sellToken` and `buyToken` methods (and most other methods in the pool). This modifier prevents the respective action whilst the pool is undergoing liquidation.

The only way to finish the liquidation is for someone (probably the protocol admin) to transfer tokens directly to the pool for all supported tokens to ensure the token balance is greater than the liquidation target for every token. This costs ERC20 tokens, gas and time (all of which scale as the length of `tokenList` increases). It also completely defeats the point of the liquidation as you're now paying a net fee to perform the liquidation (where liquidations usually reward the liquidator).

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Firstly this isn't a duplicate of #131.
> 
> Regarding the comment from the sponsor, I don't think this is true as you wouldn't be able to perform the swapping from token to token due to the `poolOngoing` modifier on the `sellToken` and `buyToken` methods (and most other methods in the pool). This modifier prevents the respective action whilst the pool is undergoing liquidation.
> 
> The only way to finish the liquidation is for someone (probably the protocol admin) to transfer tokens directly to the pool for all supported tokens to ensure the token balance is greater than the liquidation target for every token. This costs ERC20 tokens, gas and time (all of which scale as the length of `tokenList` increases). It also completely defeats the point of the liquidation as you're now paying a net fee to perform the liquidation (where liquidations usually reward the liquidator).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@djb15 
Additional Sponsor comment:
> DODO can be traded through liquidateByDODO, so we believe that this issue is invalid.

**Comment by djb15** [comment]
@hrishibhat Agree with the additional sponsor comment, that's true.

However I'd argue the issue is still a valid medium as it still costs the admin gas and tokens (the same as my justification above, despite the alternate resolution path).

For example, let's say the vault had 20 tokens, of which only 1 token had negative worth/bad debt. A malicious user could transfer some of the other 19 tokens to the vault during the DODO liquidation flow (after the `startLiquidation` call). So the admin now has to make 19 swaps, which costs the gas for 19 transactions and the fee for 19 swaps (and the time to perform all these swaps, during which the vault is "offline" for users). This is a classic case a griefing, where the scale of the griefing depends on how many tokens are in the vault.

With my recommended change this lifecycle would never occur.

**Comment by hrishibhat** [comment]
@djb15 there seems to be a couple of points for which this would be a low:
- There are no funds lost
- Spending extra gas is not valid medium
- temporary griefing
- Attacker has to keep supplying these tokens to the vault everytime

**Comment by djb15** [comment]
@hrishibhat Just checked the Sherlock docs again and yeah this is clearly a griefing attack that lasts significantly less than 1 year. So agree this is low. Apologies for the oversight!

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a valid low based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [djb15](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/48/#issuecomment-1650935492): accepted
