### ISSUE TITLE
kutugu - Fee transfer should check that the amount is not 0

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#50]
kutugu

medium

# Fee transfer should check that the amount is not 0

## Summary

DODO is deployed to BNB, and transfer zero is prohibited for BNB tokens. If you do not check that amount is 0, the user is prevented from using the protocol when fee is 0.

## Vulnerability Detail

Tokens such as BNB do not support zero-value transfer and should check that the amount is not 0 before tranfer fee, otherwise the entire tx will revert.

## Impact

When fee is 0, the user cannot interact with the protocol using tokens such as BNB, the functions such as buyToken and sellToken are unavailable.

## Code Snippet

- https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Trading.sol#L113
- https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Trading.sol#L152

## Tool used

Manual Review

## Recommendation

Check amount before transfer fee

**Comment by KuTuGu** [comment]
Escalate
The sponsor seems to think that BNB is a native token like ETH, but in fact BNB is a contract token: https://etherscan.io/address/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#code.
It is clear from the contract code that it does not support zero-value transfer.
And there is a BNB/ETH uniswap3 lp pool on mainnet: https://etherscan.io/address/0x9e7809c21ba130c1a51c112928ea6474d9a9ae3c#code
So I think contracts will interact with tokens like BNB, and the issue is valid.

**Comment by sherlock-admin2** [comment]
> Escalate
> The sponsor seems to think that BNB is a native token like ETH, but in fact BNB is a contract token: https://etherscan.io/address/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#code.
> It is clear from the contract code that it does not support zero-value transfer.
> And there is a BNB/ETH uniswap3 lp pool on mainnet: https://etherscan.io/address/0x9e7809c21ba130c1a51c112928ea6474d9a9ae3c#code
> So I think contracts will interact with tokens like BNB, and the issue is valid.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by maarcweiss** [comment]
I agree with Watsons point. The only way to assign a medium here would be if BNB is actually used as the fee token @Attens1423 . If this is the case, this should be a medium

**Comment by hrishibhat** [comment]
Sponsor comment
> In fact, in the logic of the frontend, we treat BNB as a currency similar to ETH and use WBNB to create pools and conduct transactions. Therefore, this issue does not exist.

**Comment by hrishibhat** [comment]
@KuTuGu

**Comment by KuTuGu** [comment]
Whether the issue is valid depends on whether BNB is adopted or not. I'm not sure what sherlock's criteria is, because from the audit page, DODO claims to support any token

**Comment by hrishibhat** [comment]
Result:
Low
Unique
In addition to how the bnb is used according to Sponsor comments.
Not being able to use these functions for a token is not a significant and this requires fee to be 0
Do not see an impact for a medium here. There is no loss of funds here in addition to the above points.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kutugu](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/50/#issuecomment-1649857672): rejected
