### ISSUE TITLE
kutugu - getUserQuota is smaller than the actual value, causing the quota to be bypassed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#58]
kutugu

medium

# getUserQuota is smaller than the actual value, causing the quota to be bypassed

## Summary

getUserQuota have precision error, is smaller than the actual value, causing the quota to be bypassed

## Vulnerability Detail

```solidity
            if (tokenBalance > 0) {
                tokenBalance = tokenBalance.mul(d3Vault.getExchangeRate(token));
                (uint256 tokenPrice, uint8 priceDecimal) = ID3Oracle(d3Vault._ORACLE_()).getOriginalPrice(_token);
                usedQuota = usedQuota + tokenBalance * tokenPrice / 10 ** (priceDecimal+tokenDecimals);
            }
        }
        //token price reduction
        (uint256 _tokenPrice, uint8 _priceDecimal) = ID3Oracle(d3Vault._ORACLE_()).getOriginalPrice(token);
        calculate quota
        if (isUsingQuota[token]) {
            if (isGlobalQuota[token]) {
                return (gloablQuota[token] - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;
            } else {
                return (calculateQuota(user) - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;
            }
        } else {
            return type(uint256).max;
        }
```

For `getUserQuota`, usedQuota is divided by `10 ** (_priceDecimal + tokenDecimals)` first, then subtracted by `totalQuota[token]` and then multiplied by `10 ** (_priceDecimal + tokenDecimals)`.  Let me be clear with numbers:
```shell
usedQuota = 0
tokenBalance = 0.5 ether
exchangeRate = 1e18
tokenBalance = DecimalMath.mul(tokenBalance, exchangeRate ) = 0.5e18
tokenPrice = 1e18
_priceDecimal = 1e18
tokenDecimals = 1e18
usedQuota = usedQuota + tokenBalance * tokenPrice / 10 ** (priceDecimal+tokenDecimals) = 0
```

## Impact

The accuracy error causes `usedQuota` to be incorrectly calculated to be smaller than the actual value, which allows the Quota to be bypassed to manipulate funds exceeding the threshold

## Code Snippet

- https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol#L79-L93

## Tool used

Manual Review

## Recommendation

```diff
diff --git a/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol b/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol
index 2e4d9ba..5abda88 100644
--- a/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol
+++ b/new-dodo-v3/contracts/DODOV3MM/D3Vault/periphery/D3UserQuota.sol
@@ -79,7 +79,7 @@ contract D3UserQuota is InitializableOwnable, ID3UserQuota {
             if (tokenBalance > 0) {
                 tokenBalance = tokenBalance.mul(d3Vault.getExchangeRate(token));
                 (uint256 tokenPrice, uint8 priceDecimal) = ID3Oracle(d3Vault._ORACLE_()).getOriginalPrice(_token);
-                usedQuota = usedQuota + tokenBalance * tokenPrice / 10 ** (priceDecimal+tokenDecimals);
+                usedQuota += tokenBalance;
             }
         }
         //token price reduction
@@ -87,9 +87,9 @@ contract D3UserQuota is InitializableOwnable, ID3UserQuota {
         //calculate quota
         if (isUsingQuota[token]) {
             if (isGlobalQuota[token]) {
-                return (gloablQuota[token] - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;
+                return gloablQuota[token] * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice - usedQuota;
             } else {
-                return (calculateQuota(user) - usedQuota) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice;
+                return calculateQuota(user) * 10 ** (_priceDecimal + tokenDecimals) / _tokenPrice - usedQuota;
             }
         } else {
             return type(uint256).max;
```

**Comment by IAm0x52** [comment]
Escalate

This is not a dupe of #193. The precision loss is never more than a dollar. Considering the size of quotes and that they are always value in USD this should be a low issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not a dupe of #193. The precision loss is never more than a dollar. Considering the size of quotes and that they are always value in USD this should be a low issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KuTuGu** [comment]
Yes, this is not a repeat of #193, but the precision loss is definitely not 1. 
As the specific example i provided above, the user spent 0.5 ether, but the calculated quota is 0, which allows the user to bypass the quota to spend.
Assume `tokenPrice = _priceDecimal = tokenDecimals = 1e18`, `tokenBalance * tokenPrice / 10 ** (priceDecimal+tokenDecimals) = 0`, The maximum value of tokenBalance can be `0.99 ether` and the usedQuota is `0`.

**Comment by IAm0x52** [comment]
In you example you've assumed that the price is 1e18 so in that case the precision loss is 0.5 USD. If you assume a realistic value for ETH like 1800e18 then the quota would be 900.

**Comment by KuTuGu** [comment]
You assume that price is greater than 1, right? But the tokenPrice might be less than 1, that is `tokenPrice / 10 ** priceDecimal < 1`, so `tokenBalance * tokenPrice / 10 ** (priceDecimal+tokenDecimals) = 0` could still be 0, if `tokenBalance / tokendecimal < priceDecimal / tokenPrice`.

**Comment by KuTuGu** [comment]
Oh, you are right, the accuracy loss can only be $1.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a valid low based on the above comments and its impact

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/58/#issuecomment-1650737950): accepted
